### ISSUE TITLE
No warnings on invalid command line

### ISSUE THREAD

**Issue by kornysietsma** [macourtney/drift#18]
This may be just an annoyance, but it wasted us a bunch of time.

If you run "lein migrate [version number]" by accident (instead of "lein migrate -version [version number]") the version number is silently ignored, and instead drift migrates to the latest version.

This is rather confusing!

**Comment by Sardtok** [comment]
Oops, @macourtney. This didn't auto close as Github doesn't recognize "fixing #18" as a commit fixing the issue.
