### ISSUE TITLE
No documentation for rollback/down a migration

### ISSUE THREAD

**Issue by taha-webonise** [macourtney/drift#33]
Spent some time to find a way to rollback my last 2 migrations from command line. Found no documentation here and finally have to do manually in database.

**Comment by macourtney** [comment]
There is some documentation on how to do this in the readme file. However, the documentation doesn't cover your exact situation.

If the last 3 migrations you have are numbered 1, 2, and 3. and you want to roll back to 1, removing migration 2 and 3 from your database, simply use "lein migrate 1".

**Comment by macourtney** [comment]
I forgot the "-version". To migrate to version 1 in the above example use, "lein migrate -version 1".
